{
 "title": "System Monitoring",
 "tags": [ "alerts" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Virtual Mem Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Free Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_filesystem_files_free", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Targets Online",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(up)" }
   ]
  }
 ]
}